# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' time index that triggers a symmetric CUSUM filter
#'
#' @param x a vector of time series to be filtered
#' @param h a positive number for the thresholds
#'
#' @examples
#' set.seed(1)
#' x <- runif(100, 1, 3)
#' h <- 1.5
#' i_CUSUM <- istar_CUSUM(x,h)
#' plot(x)
#' abline(v=i_CUSUM, lty = 2)
#'
#' ## Comparing C and R versions
#' set.seed(1)
#' x <- runif(1000000, 1, 3)
#' h <- 1.5
#'
#' start_time <- Sys.time()
#' i_CUSUM <- istar_CUSUM(x,h)
#' end_time <- Sys.time()
#' C_time <- end_time - start_time
#'
#' start_time <- Sys.time()
#' i_CUSUM_R <- istar_CUSUM_R(x,h)
#' end_time <- Sys.time()
#' R_time <- end_time - start_time
#' cat("C and R time: ", C_time, R_time)
#' all(i_CUSUM-i_CUSUM_R==0)
#' @export
istar_CUSUM <- function(x, h) {
    .Call(`_fmlr_istar_CUSUM`, x, h)
}

